# Generated by Django 4.2.30 on 2026-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('personnel', models.CharField(max_length=80)),
                ('item', models.CharField(max_length=80)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
